### ISSUE TITLE
null user when name is cancelled

### ISSUE THREAD

**Issue by Williamgood** [zcmoore/DecisionTheater#2]
A null user is submitted into the server controller when cancel is hit entering the name and remains there as long as the window(tab) is opened. 

Also somewhat related is "Name required to enter Decision Theatre" that appears when cancelled appears partially under the menu bar.

**Comment by zcmoore** [comment]
Regarding the second issue, can you provide a screenshot? I can't reproduce it.

**Comment by Williamgood** [comment]
![capture](https://cloud.githubusercontent.com/assets/1197671/8048858/9789a26e-0e0b-11e5-971e-50d94eabf034.PNG)

Forgot to mention Firefox (at least on both of my computers.) Not sure what other browsers may look like.

**Comment by zcmoore** [comment]
Is that the entire screen? Also, is this after a successful login, or after pressing cancel?

**Comment by Williamgood** [comment]
Hitting cancel. Yeah it's pretty much entire screen (theres technically more white to the right and left)

**Comment by zcmoore** [comment]
The source of this issue is that Firefox has issues with the css "top" value in addition to webkit transforms. A solution is committed above by replacing top with padding, however this causes a scrollbar issue (see #3)

Overall, the scrollbar issue is minor, and better than this improper display. However, #3 should be looked into when we have the time.
